"""phase 3.5: verification tokens

Revision ID: 8381efd24bd8
Revises: 68e20993f2cd
Create Date: 2026-09-22 09:54:16.576793
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8381efd24bd8'
down_revision: Union[str, None] = '68e20993f2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tokens'))
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_verification_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_verification_tokens_user_purpose', ['user_id', 'purpose'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_tokens_user_purpose')
        batch_op.drop_index(batch_op.f('ix_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_expires_at'))

    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
